name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  erlang_23:
    runs-on: ubuntu-latest

    container:
      image: dr2.rbkmoney.com/rbkmoney/build-erlang:491bc06c745a07c6fe9e8b5dbbe958e8e0b82c4c

    steps:
    - uses: actions/checkout@v2
